
name: 'perekrestokvprok'
version: '1.0.0'
config-version: 2

profile: 'perekrestokvprok'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
tests:
  +store_failures: true
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "docs_netlify"  
clean-targets:         
  - "target"
  - "docs_netlify"
  - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  perekrestokvprok:
    staging:
      +materialized: view
