
version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.9.9
      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout

      - run:
          run: setup_creds
          command: |
            echo $BIGQUERY_SERVICE_ACCOUNT_JSON > ${HOME}/bigquery-service-key.json

      - restore_cache:
          key: deps1-{{ .Branch }}

      - run:
          name: "Setup dbt"
          command: |
            python3 -m venv dbt_venv
            . dbt_venv/bin/activate

            python -m pip install --upgrade pip setuptools
            python -m pip install --pre dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery

            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml

      - run:
          name: "Run Tests - Postgres"
          environment:
            POSTGRES_TEST_HOST: localhost
            POSTGRES_TEST_USER: root
            POSTGRES_TEST_PASS: ''
            POSTGRES_TEST_PORT: 5432
            POSTGRES_TEST_DBNAME: circle_test
          command: |
            . dbt_venv/bin/activate
            cd integration_tests
            dbt deps --target postgres
            dbt run-operation create_source_table --target postgres
            dbt seed --target postgres --full-refresh
            dbt run --target postgres
            dbt test --target postgres

      - run:
          name: "Run Tests - Redshift"
          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps --target redshift
            dbt run-operation create_source_table --target redshift
            dbt seed --target redshift --full-refresh
            dbt run --target redshift
            dbt test --target redshift

      - run:
          name: "Run Tests - Snowflake"
          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps --target snowflake
            dbt run-operation create_source_table --target snowflake
            dbt seed --target snowflake --full-refresh
            dbt run --target snowflake
            dbt test --target snowflake

      - run:
          name: "Run Tests - BigQuery"
          environment:
              BIGQUERY_SERVICE_KEY_PATH: "/home/circleci/bigquery-service-key.json"

          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps --target bigquery
            dbt run-operation create_source_table --target bigquery
            dbt seed --target bigquery --full-refresh
            dbt run --target bigquery
            dbt test --target bigquery


      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "dbt_venv"
