name: 'dbt_labs_materialized_views'
version: '0.2.0'
config-version: 2
require-dbt-version: ">=1.0.0"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seed"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
